services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "stats"]
      interval: 5s
      timeout: 5s
      retries: 20

  stats-server:
    build: ./stats-service/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin", "-d", "ewm" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=5050,server=y,suspend=n"

volumes:
  ewm-db-data:
  stats-db-data:
