services:
  stats-server:
    build: ./stats-service/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator" ]
      interval: 10s
      timeout: 5s
      retries: 20

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 20

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm_user
      - SPRING_DATASOURCE_PASSWORD=12345

  # база основного сервиса
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5
